# Generated by Django 3.1.3 on 2020-11-30 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('hamburguer_de_carne', 'Hambúrguer de carne'), ('hamburguer_de_frango', 'Hambúrguer de frango'), ('acompanhamento', 'Acompanhamento'), ('sobremesa', 'Sobremesa'), ('vegetariano', 'Vegetariano'), ('xposservico', 'X-Pós Serviço'), ('xcansado', 'X-Cansado')], default='geral', max_length=50)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cupom', models.CharField(max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcansado.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcansado.produto')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
    ]
