# Generated by Django 3.1.3 on 2020-12-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcansado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('hamburguer_de_carne', 'Hambúrguer de carne'), ('hamburguer_de_frango', 'Hambúrguer de frango'), ('acompanhamento', 'Acompanhamento'), ('sobremesa', 'Sobremesa'), ('vegetariano', 'Vegetariano'), ('xposservico', 'X-Pós Serviço'), ('xcansado', 'X-Cansado')], default='xcansado', max_length=50),
        ),
    ]
